#ifndef GLENDA_ERROR_H
#define GLENDA_ERROR_H

typedef enum
{
    GLENDA_SUCCESS = 0,
    GLENDA_ERR_INVALID_CAP = 1,
    GLENDA_ERR_PERMISSION_DENIED = 2,
    GLENDA_ERR_INVALID_ENDPOINT = 3,
    GLENDA_ERR_INVALID_OBJ_TYPE = 4,
    GLENDA_ERR_INVALID_METHOD = 5,
    GLENDA_ERR_MAPPING_FAILED = 6,
    GLENDA_ERR_INVALID_SLOT = 7,
    GLENDA_ERR_OUT_OF_MEMORY = 8,
    GLENDA_ERR_INVALID_ARGS = 9,
    GLENDA_ERR_INVALID_PROTOCOL = 10,
    GLENDA_ERR_INVALID_PARAM = 11,
    GLENDA_ERR_CNODE_FULL = 12,
    GLENDA_ERR_NOT_SUPPORTED = 13,
    GLENDA_ERR_TIMEOUT = 14,
    GLENDA_ERR_INTERRUPTED = 15,
    GLENDA_ERR_BUSY = 16,
    GLENDA_ERR_NOT_FOUND = 17,
    GLENDA_ERR_ALREADY_EXISTS = 18,
    GLENDA_ERR_IO = 19,
    GLENDA_ERR_BUFFER_OVERFLOW = 20,
    GLENDA_ERR_NOT_IMPLEMENTED = 21,
    GLENDA_ERR_OUT_OF_SLOTS = 22,
    GLENDA_ERR_NOT_INITIALIZED = 23,
    GLENDA_ERR_DEVICE_ERROR = 24,
    GLENDA_ERR_UNKNOWN = 255
} glenda_error_t;

#endif /* GLENDA_ERROR_H */
