#ifndef GLENDA_METHOD_H
#define GLENDA_METHOD_H

// IPC Methods
#define METHOD_IPC_SEND 1
#define METHOD_IPC_RECV 2
#define METHOD_IPC_CALL 3
#define METHOD_IPC_NOTIFY 4

// Reply
#define METHOD_REPLY 1

// TCB Methods
#define METHOD_TCB_CONFIGURE 1
#define METHOD_TCB_SET_PRIORITY 2
#define METHOD_TCB_SET_ENTRYPOINT 3
#define METHOD_TCB_SET_FAULT_HANDLER 4
#define METHOD_TCB_SET_AFFINITY 5
#define METHOD_TCB_SET_REGISTERS 6
#define METHOD_TCB_RESUME 7
#define METHOD_TCB_SUSPEND 8

// PageTable Methods
#define METHOD_PT_MAP 1

// CNode Methods
#define METHOD_CNODE_MINT 1
#define METHOD_CNODE_COPY 2
#define METHOD_CNODE_DELETE 3
#define METHOD_CNODE_REVOKE 4
#define METHOD_CNODE_DEBUG_PRINT 5

// Untyped Methods
#define METHOD_UNTYPED_RETYPE 1

// IRQ Methods
#define METHOD_IRQ_SET_NOTIFICATION 1
#define METHOD_IRQ_ACK 2
#define METHOD_IRQ_CLEAR_NOTIFICATION 3
#define METHOD_IRQ_SET_PRIORITY 4

// Kernel Methods
#define METHOD_KERNEL_CONSOLE_PUT_STR 1
#define METHOD_KERNEL_CONSOLE_GET_CHAR 2
#define METHOD_KERNEL_CONSOLE_GET_STR 3
#define METHOD_KERNEL_SHELL 4

// VSpace Methods
#define METHOD_VSPACE_MAP 1
#define METHOD_VSPACE_UNMAP 2
#define METHOD_VSPACE_MAP_TABLE 3
#define METHOD_VSPACE_SETUP 4
#define METHOD_VSPACE_DEBUG_PRINT 5

#endif
